version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
- package-ecosystem: npm
  directory: "/src/API"
  groups:
    babel:
      patterns:
        - "@babel/*"
    typescript-eslint:
      patterns:
        - "@typescript-eslint/*"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  open-pull-requests-limit: 99
- package-ecosystem: nuget
  directory: "/"
  groups:
    Microsoft.OpenApi:
      patterns:
        - Microsoft.OpenApi*
    OpenTelemetry:
      patterns:
        - OpenTelemetry*
    Pyroscope:
      patterns:
        - Pyroscope*
    xunit:
      patterns:
        - Verify.Xunit*
        - xunit*
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  open-pull-requests-limit: 99
