os: Visual Studio 2015
version: 1.0.{build}

environment:
  CLI_VERSION: Latest

install:
  - ps: mkdir -Force ".\.dotnetcli\" | Out-Null
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.ps1" -OutFile ".\.dotnetcli\install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\.dotnetcli\install.ps1 -version "$env:CLI_VERSION" -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
  - ps: npm install -g bower
  - ps: npm install -g gulp

build_script:
  - ps: dotnet --info
  - ps: .\Build.cmd

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off
