os: Visual Studio 2019
version: 3.0.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

cache:
  - src\API\node_modules
  - '%APPDATA%\npm\node_modules'
  - '%APPDATA%\npm-cache'

install:
  - ps: iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI"
  - pwsh: npm install --global npm

build_script:
  - pwsh: .\Build.ps1

after_build:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "artifacts\coverage.cobertura.xml"

artifacts:
  - path: artifacts\publish

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off
