imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:
  bombardier:
    channel: current
  server:
    source:
      repository: https://github.com/martincostello/api
      branchOrCommit: main
      project: src/API/API.csproj
    channel: current
    readyStateText: Application started.

scenarios:
  root:
    application:
      job: server
      framework: net8.0
    load:
      job: bombardier
      framework: net8.0
      variables:
        serverPort: 5000
        path: /
  guid:
    application:
      job: server
      framework: net8.0
    load:
      job: bombardier
      framework: net8.0
      variables:
        serverPort: 5000
        path: /tools/guid
  openapi:
    application:
      job: server
      framework: net8.0
    load:
      job: bombardier
      framework: net8.0
      variables:
        serverPort: 5000
        path: /openapi/api.json
  time:
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 5000
        path: /time

profiles:
  local:
    variables:
      serverAddress: localhost
    jobs:
      application:
        endpoints:
          - http://localhost:5010
      load:
        endpoints:
          - http://localhost:5010
