<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" />
  <PropertyGroup>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <IsAspireHost>true</IsAspireHost>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <UserSecretsId>api.martincostello.com-AppHost</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" NoWarn="RT0003" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\API\API.csproj" />
  </ItemGroup>
</Project>
