name: automerge
on:
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@c9bd1823770819dc8fb8a5db2d11a3a95fbe9b07"
        env:
          GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
          MERGE_LABELS: "automerge,!blocked"
