name: container-scan

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions: {}

env:
  FORCE_COLOR: 3
  TERM: xterm

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:

      - name: Configure Trivvy
        id: configure
        shell: pwsh
        run: |
          $registry = "${env:GITHUB_REPOSITORY_OWNER}.azurecr.io"
          $image = "${registry}/${env:GITHUB_REPOSITORY}:latest".ToLowerInvariant()
          "container-image=${image}" >> ${env:GITHUB_OUTPUT}

      - name: Run Trivy (SARIF)
        uses: aquasecurity/trivy-action@fd25fed6972e341ff0007ddb61f77e88103953c2 # v0.21.0
        env:
          TRIVY_USERNAME: ${{ secrets.TRIVY_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.TRIVY_PASSWORD }}
        with:
          image-ref: ${{ steps.configure.outputs.container-image }}
          format: 'sarif'
          ignore-unfixed: true
          limit-severities-for-sarif: true
          output: 'trivy.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ !cancelled() }}
        with:
          sarif_file: 'trivy.sarif'

      - name: Run Trivy (Table)
        uses: aquasecurity/trivy-action@fd25fed6972e341ff0007ddb61f77e88103953c2 # v0.21.0
        env:
          TRIVY_USERNAME: ${{ secrets.TRIVY_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.TRIVY_PASSWORD }}
        with:
          image-ref: ${{ steps.configure.outputs.container-image }}
          format: 'json'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
