name: dependency-review

on:
  pull_request:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly

permissions: {}

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          filter: 'tree:0'
          show-progress: false

      - name: Review dependencies
        uses: actions/dependency-review-action@v4
