name: deploy
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Sync main with deploy
        run: |
          git checkout deploy
          git fetch origin main:deploy
          git push origin deploy
