name: deploy

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    name: apimartincostello-uksouth
    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Build and Publish
      shell: pwsh
      run: ./build.ps1 -OutputPath './artifacts/api'
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        NUGET_XMLDOC_MODE: skip

    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: apimartincostello-uksouth
        package: './artifacts/api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
