name: deploy

on:
  push:
    branches: [ deploy ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2

    - name: Build and Publish
      shell: pwsh
      run: ./build.ps1 -SkipTests
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        NUGET_XMLDOC_MODE: skip

    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      if: ${{ github.ref == 'refs/heads/deploy' && runner.os == 'Windows' }}
      with:
        app-name: apimartincostello-uksouth
        package: './artifacts/publish'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
