name: deploy
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Sync main with deploy
        run: |
          git fetch origin deploy
          git checkout deploy
          git rebase main
          git push origin deploy
