name: lint

on:
  push:
    branches-ignore: [ master, deploy ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v2.0.0
        env:
          VALIDATE_JAVASCRIPT_STANDARD: false
