name: spectral

on:
  pull_request:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly
  workflow_dispatch:

permissions: {}

jobs:
  spectral:
    runs-on: ubuntu-24.04

    env:
      # renovate: datasource=npm depName=spectral-cli packageName=@stoplight/spectral-cli
      SPECTRAL_CLI_VERSION: '6.16.1'

    permissions:
      contents: read

    steps:

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0

    - name: Setup Node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: '24.x'

    - name: Install Spectral
      run: npm install --global "@stoplight/spectral-cli@${SPECTRAL_CLI_VERSION}"

    - name: Generate OpenAPI document
      run: dotnet build ./src/API

    - name: Run Spectral
      run: spectral lint "./artifacts/openapi/*" --fail-severity warn --format github-actions
